# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

services:
    sinepu.repository.tickets_templates:
        class: Tickets\Infrastructure\Repository\Doctrine\TicketsTemplatesRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - 'Tickets\Domain\TicketsTemplate'


    sinepu.repository.tickets:
        class: Tickets\Infrastructure\Repository\Doctrine\TicketsRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - 'Tickets\Domain\Ticket'
    sinepu.repository.tickets_events:
        class: Tickets\Infrastructure\Repository\Doctrine\TicketsEventRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - 'Tickets\Domain\TicketEvent'

    sinepu.query.ticket_templates:
        class: Tickets\Infrastructure\Query\TicketsTemplatesQuery
        arguments:
          - "@sinepu.repository.tickets_templates"

    sinepu.query.tickets:
        class: Tickets\Infrastructure\Query\TicketsQuery
        arguments:
          - "@sinepu.repository.tickets"

    sinepu.query.tickets_events:
        class: Tickets\Infrastructure\Query\TicketEventQuery
        arguments:
          - "@sinepu.repository.tickets_events"


    sinepu.handler.create_ticket:
        class: Tickets\Application\Command\CreateTicketHandler
        arguments:
          - '@sinepu.repository.tickets'
          - '@sinepu.repository.tickets_events'

    bundle.form.ticket_type:
        class: AppBundle\Form\TicketType
        arguments:
          - '@sinepu.query.ticket_templates'
        tags:
          - {name: form.type}

    bundle.form.ticket_template_type:
        class: AppBundle\Form\TicketTemplateForm

    sinepu.handler.create_ticket_type:
        class: Tickets\Application\Command\CreateTicketTemplateHandler
        arguments:
          - '@sinepu.repository.tickets_templates'

    sinepu.handler.create_ticket_type_command:
        class: Tickets\Application\Command\CreateTicketTemplateCommand
