Tickets\Domain\Ticket:
    type: entity
    table: ticket
    repositoryClass: Tickets\Infrastructure\Repository\Doctrine\TicketsRepository
    id:
        uuid:
            type: uuid
            generator:
                strategy: NONE
    fields:
        type:
            type: string
        createdAt:
            type: datetime
