Tickets\Domain\TicketTemplate:
    type: entity
    table: TicketTemplate
    repositoryClass: Tickets\Infrastructure\Repository\Doctrine\TicketTemplateRepository
    id:
        uuid:
            type: uuid
            generator:
                strategy: NONE
    fields:
        name:
            type: string
        content:
            type: string
        annotations:
            type: string
