Tickets\Domain\Ticket:
    type: entity
    id:
        uuid:
            type: uuid
            generator: { strategy: AUTO }
    fields:
        uuid:
            type: uuid
        content:
            type: text
        type:
            type: array
        files:
            type: array
        createdAt:
            type: datetime
        updatedAt:
            type: datetime